---

- name: Install dependencies
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Install docker
  package:
    name: docker-ce
    state: present
